version: '3.8'

services:
  chromadb:
    image: chromadb/chroma:latest
    ports:
      - "8000:8000"
    environment:
      - CHROMA_SERVER_HOST=0.0.0.0
      - CHROMA_SERVER_HTTP_PORT=8000
    volumes:
      - chroma_data:/chroma/chroma
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000/api/v1/heartbeat"]
      interval: 30s
      timeout: 10s
      retries: 3

  app:
    build: .
    ports:
      - "3000:3000"
    environment:
      - OPENAI_KEY=${OPENAI_KEY}
      - OMI_APP_ID=${OMI_APP_ID}
      - OMI_APP_SECRET=${OMI_APP_SECRET}
      - CHROMA_URL=http://chromadb:8000
      - PORT=3000
    depends_on:
      chromadb:
        condition: service_healthy
    restart: unless-stopped

volumes:
  chroma_data:
